android cross compilation

diff --git a/dist/gcc-compatible/configure b/dist/gcc-compatible/configure
--- a/dist/gcc-compatible/configure
+++ b/dist/gcc-compatible/configure
@@ -7,6 +7,15 @@ if [[ $CC == "" ]]; then
   CC=cc
 fi
 
+# XXX: Only some defaults for testing. Remove before merging
+# Get the toolchain at https://developer.android.com/ndk/downloads/
+if [[ $SYSROOT == "" ]]; then
+  SYSROOT="$NDK/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/"
+fi
+if [[ $NDK_TOOLCHAIN == "" ]]; then
+  NDK_TOOLCHAIN="$NDK/toolchains/llvm/prebuilt/darwin-x86_64/"
+fi
+
 # This script mostly detects the presence of ocamlfind as well as various ocaml
 # packages
 
@@ -79,25 +88,23 @@ int main() {
   return 0;
 }
 EOF
-  $CC -I. -I../kremlin/include -I../kremlin/kremlib/dist/minimal -march=native -O3 $file -o $out && $out > $out.test
-  $CC -I. -I../kremlin/include -I../kremlin/kremlib/dist/minimal -DBROKEN_INTRINSICS -march=native -O3 $file -o $out && $out > $out.ref
+  $CC $CROSS_CFLAGS -I. -I../kremlin/include -I../kremlin/kremlib/dist/minimal -march=native -O3 $file -o $out && $out > $out.test
+  $CC $CROSS_CFLAGS -I. -I../kremlin/include -I../kremlin/kremlib/dist/minimal -DBROKEN_INTRINSICS -march=native -O3 $file -o $out && $out > $out.ref
   diff $out.test $out.ref
 }
 
 detect_uint128 () {
   local file=$(mktemp /tmp/testint128.XXXXXXX).c
   echo "unsigned __int128 x = 0;" > $file
-  $CC -c $file -o /dev/null
+  $CC $CROSS_CFLAGS -c $file -o /dev/null
 }
 
 detect_x64 () {
-  [[ $(uname -m) == "x86_64" ]]
+  [[ $target_arch == "x86_64" ]]
 }
 
 detect_arm () {
-  [[ $(uname -m | cut -c 1-3) == "arm" ]] || \
-  [[ $(uname -m | cut -c 1-7) == "aarch64" ]] || \
-  [[ "$1" == "arm" ]] || [[ "$1" == "aarch64" ]];
+  [[ $target_arch == "arm" ]] || [[ $target_arch == "aarch64" ]];
 }
 
 detect_arm_cc () {
@@ -113,7 +120,7 @@ int main () {
   return 0;
 }
 EOF
-  $CC -I. -march=armv8-a+simd -c $file -o /dev/null
+  $CC $CROSS_CFLAGS -I. -march=armv8-a+simd -c $file -o /dev/null
 }
 
 detect_broken_xcode () {
@@ -146,7 +153,20 @@ int main () {
   return 0;
 }
 EOF
-  $CC -Werror -c $file -o /dev/null
+  $CC $CROSS_CFLAGS -Werror -c $file -o /dev/null
+}
+
+# Usage info
+show_help () {
+  # XXX: Alternatively do a cat help.txt
+  printf "\nUsage: configure -target <triple>\n\n"
+  printf "This script configures HACL/Evercrypt. You can specify the following options:\n\n"
+  printf "    -target       Specify the target triple for the build. This follows the\n"
+  printf "                  Clang target triple convention.\n"
+  printf "                  Details: https://clang.llvm.org/docs/CrossCompilation.html\n"
+  printf "                  Currently supported triples are:\n"
+  printf "                  * aarch64-linux-android\n"
+  printf "\n"
 }
 
 # Main auto-detection
@@ -159,49 +179,63 @@ all_args=("$@")
 while [ $# -gt 0 ]; do
     case "$1" in
         -target) build_target="$2"; shift ;;
-        -arm) build_arch="arm" ;;
-        -aarch64) build_arch="aarch64" ;;
+        --help) show_help; exit 0 ;;
     esac
     shift
 done
 
-if [ ! -z "$build_arch" ]; then
-  echo "Doing cross build for $build_arch. Make sure that your toolchain is configured properly."
-  echo "CFLAGS += -DCROSS_COMPILATION -DTARGET_ARCH=$build_arch" >> Makefile.config
-else
-  build_arch=$(uname -m)
-fi
+# We need to have the following to decide what to build and what not.
+# * build_target: the llvm target triplet, e.g. armv7a-none-eabi
+# This is being decomposed into the following information.
+# * target_arch: the target architecture, e.g. aarch64, arm, x86_64, i386
+# * target_sys: the target system, e.g. none, linux, win32, darwin
+# * target_abi: the target abi, e.g. eabi, gnu, android, macho
 
 if [ ! -z "$build_target" ]; then
   echo "Doing cross build for $build_target. Make sure that your toolchain is configured properly."
-  if [[ "$build_target" == "iOS" ]]; then
-    export SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
+  if [[ "$build_target" == "aarch64-linux-android" ]]; then
+    target_arch="aarch64"
+    target_sys="Linux"
+    target_abi="android"
+    AR=$NDK_TOOLCHAIN/aarch64-linux-android/ar
+    CROSS_TARGET="-target $build_target"
+    CROSS_SYSROOT="--sysroot=$SYSROOT"
+    CROSS_INCLUDES="-I$SYSROOT/usr/include/"
+  else
+    show_help
+    exit 0
   fi
+  CROSS_CFLAGS="$CROSS_TARGET $CROSS_SYSROOT $CROSS_INCLUDES"
+  echo "CFLAGS += $CROSS_CFLAGS" >> Makefile.config
+else
+  target_arch=$(uname -m)
+  target_sys=$(uname)
+  target_abi="native"
 fi
 
-if detect_arm $build_arch; then
+if detect_arm; then
   echo "... detected ARM platform"
-  echo "... $build_arch does not support 256-bit arithmetic"
+  echo "... $build_target does not support 256-bit arithmetic"
   echo "BLACKLIST += $(ls *CP256*.c *_256.c *_Vec256.c | xargs)" >> Makefile.config
-  echo "... $build_arch does not support legacy vale stubs"
+  echo "... $build_target does not support legacy vale stubs"
   echo "BLACKLIST += evercrypt_vale_stubs.c" >> Makefile.config
   echo "CFLAGS += -DLib_IntVector_Intrinsics_vec256=\"void *\"" >> Makefile.config
   if detect_arm_cc; then
-    echo "... $CC can cross-compile to ARM64 with SIMD"
+    echo "... $CC $CROSS_CFLAGS can cross-compile to ARM64 with SIMD"
     echo "CFLAGS_128 = -march=armv8-a+simd" >> Makefile.config
     echo "#define IS_ARM_8 1" >> config.h
   else
-    echo "$CC cannot compile 128-bit vector arithmetic, disabling"
+    echo "$CC $CROSS_CFLAGS cannot compile 128-bit vector arithmetic, disabling"
     echo "BLACKLIST += $(ls *CP128*.c *_128.c *_Vec128.c | xargs)" >> Makefile.config
     echo "#define IS_ARM_7 1" >> config.h
     echo "CFLAGS += -DLib_IntVector_Intrinsics_vec128=\"void *\"" >> Makefile.config
   fi
 fi
 
-if [[ ! detect_x64 ]] || [[ ! -z "$build_target" ]]; then
-  echo "$build_arch does not support x64 assembly, disabling Curve64"
+if ! detect_x64; then
+  echo "$build_target does not support x64 assembly, disabling Curve64"
   echo "BLACKLIST += Hacl_Curve25519_64.c $(ls Hacl_HPKE_Curve64_*.c | xargs)" >> Makefile.config
-  echo "$build_arch does not support _addcarry_u64, using a C implementation"
+  echo "$build_target does not support _addcarry_u64, using a C implementation"
   echo "#define BROKEN_INTRINSICS 1" >> config.h
   echo "#define IS_NOT_X64 1" >> config.h
 else
@@ -222,7 +256,7 @@ fi
 if ! detect_uint128; then
   # Explicitly not supporting compilation with MSVC, which would entail not
   # defining KRML_VERIFIED_UINT128.
-  echo "$CC does not support unsigned __int128 -- using a fallback verified implementation"
+  echo "$CC $CROSS_CFLAGS does not support unsigned __int128 -- using a fallback verified implementation"
   echo "CFLAGS += -DKRML_VERIFIED_UINT128" >> Makefile.config
 fi
 
@@ -231,7 +265,7 @@ if ! detect_ocaml; then
   echo "DISABLE_OCAML_BINDINGS=1" >> Makefile.config
 fi
 
-if [[ $(uname) == "Linux" ]]; then
+if [[ $target_sys == "Linux" ]]; then
   if check_explicit_bzero; then
     echo "... glibc is recent enough for explicit_bzero"
   else
