With @kachoc, clean things up a little more

diff --git a/dist/configure b/dist/configure
--- a/dist/configure
+++ b/dist/configure
@@ -12,8 +12,8 @@ if [[ $CC == "" ]]; then
   CC=cc
 fi
 
-# This script mostly detects the presence of ocamlfind as well as various ocaml
-# packages
+# Helpers to help do feature or bug detection
+# -------------------------------------------
 
 detect_ocamlfind () {
   package=$1
@@ -95,37 +95,6 @@ detect_uint128 () {
   $CC $CROSS_CFLAGS -c $file -o /dev/null
 }
 
-detect_x64 () {
-  [[ $target_arch == "x86_64" ]]
-}
-
-detect_x86 () {
-  [[ $target_arch == "i386" ]] || [[ $target_arch == "i686" ]] || \
-  [[ $target_arch == "i86pc" ]] || [[ $target_arch == "ia32" ]]
-}
-
-detect_arm () {
-  # On Raspberry pi, uname -m is armv6l or armv7l so we need to cut!
-  [[ $(echo $target_arch | cut -c 1-3) == "arm" ]] || \
-  [[ $target_arch == "aarch64" ]]
-}
-
-detect_arm_cc () {
-  local file=$(mktemp /tmp/testvec128.XXXXXXX).c
-  cat > $file <<EOF
-#include <libintvector.h>
-
-int main () {
-  uint8_t block[32] = { 0 };
-  Lib_IntVector_Intrinsics_vec128 b1 = Lib_IntVector_Intrinsics_vec128_load_le(block);
-  Lib_IntVector_Intrinsics_vec128 b2 = Lib_IntVector_Intrinsics_vec128_load_le(block + 16);
-  Lib_IntVector_Intrinsics_vec128 test = Lib_IntVector_Intrinsics_vec128_interleave_high64(b1, b2);
-  return 0;
-}
-EOF
-  $CC $CROSS_CFLAGS -I. -march=armv8-a+simd -c $file -o /dev/null
-}
-
 detect_broken_xcode () {
   # For posterity, here are a list of things that don't work
   # - checking if cc will compile curve25519-inline.h
@@ -159,7 +128,43 @@ EOF
   $CC $CROSS_CFLAGS -Werror -c $file -o /dev/null
 }
 
+# Target platform detection
+# -------------------------
+
+detect_x64 () {
+  [[ $target_arch == "x86_64" ]]
+}
+
+detect_x86 () {
+  [[ $target_arch == "i386" ]] || [[ $target_arch == "i686" ]] || \
+  [[ $target_arch == "i86pc" ]] || [[ $target_arch == "ia32" ]]
+}
+
+detect_arm () {
+  # On Raspberry pi, uname -m is armv6l or armv7l so we need to cut!
+  [[ $(echo $target_arch | cut -c 1-3) == "arm" ]] || \
+  [[ $target_arch == "aarch64" ]]
+}
+
+detect_arm_cc () {
+  local file=$(mktemp /tmp/testvec128.XXXXXXX).c
+  cat > $file <<EOF
+#include <libintvector.h>
+
+int main () {
+  uint8_t block[32] = { 0 };
+  Lib_IntVector_Intrinsics_vec128 b1 = Lib_IntVector_Intrinsics_vec128_load_le(block);
+  Lib_IntVector_Intrinsics_vec128 b2 = Lib_IntVector_Intrinsics_vec128_load_le(block + 16);
+  Lib_IntVector_Intrinsics_vec128 test = Lib_IntVector_Intrinsics_vec128_interleave_high64(b1, b2);
+  return 0;
+}
+EOF
+  $CC $CROSS_CFLAGS -I. -march=armv8-a+simd -c $file -o /dev/null
+}
+
 # Usage info
+# ----------
+
 show_help () {
   printf "\nUsage: configure -target <triple>\n\n"
   printf "This script configures HACL/Evercrypt. You can specify the following options:\n\n"
@@ -203,6 +208,9 @@ done
 # * target_sys: the target system, e.g. none, linux, win32, darwin
 # * target_abi: the target abi, e.g. eabi, gnu, android, macho
 
+# If the user provided a build target via a command-line option, fill
+# target_{arch,sys,abi} accordingly; otherwise, query the host via uname for
+# these parameteres and assume we don't do cross-compilation.
 if [ ! -z "$build_target" ]; then
   echo "Doing cross build for $build_target. Make sure that your toolchain is configured properly."
   if [[ "$build_target" == "aarch64-none-linux-android" ]]; then
@@ -280,132 +288,95 @@ supports_128=false
 supports_256=false
 supports_vale=false
 supports_inline_asm=false
-# TODO: broken intrinsics
+supports_intrinsics=false
 
 if detect_arm; then
   echo "... detected ARM platform"
+  # TODO: poorly worded; rename detect_arm_cc into detect_neon_compiler or
+  # something
   if detect_arm_cc; then
-    echo "... $build_target supports 128-bit arithmetic"
+    echo "... $build_target supports 128-bit NEON"
     supports_128=true
     echo "... $CC $CROSS_CFLAGS can cross-compile to ARM64 with SIMD"
     echo "CFLAGS_128 = -march=armv8-a+simd" >> Makefile.config
-    echo "#define IS_ARM_8 1" >> config.h
-  else
-    echo "#define IS_ARM_7 1" >> config.h
   fi
 fi
-
-: '
-if detect_arm; then
-  echo "... detected ARM platform"
-  echo "... $build_target does not support 256-bit arithmetic"
-  echo "BLACKLIST += $(ls *CP256*.c *_256.c *_Vec256.c | xargs)" >> Makefile.config
-  echo "... $build_target does not support legacy vale stubs"
-  echo "BLACKLIST += evercrypt_vale_stubs.c" >> Makefile.config
-  echo "#define Lib_IntVector_Intrinsics_vec256 void *" >> config.h
-  if detect_arm_cc; then
-    echo "... $CC $CROSS_CFLAGS can cross-compile to ARM64 with SIMD"
-    echo "CFLAGS_128 = -march=armv8-a+simd" >> Makefile.config
-    echo "#define IS_ARM_8 1" >> config.h
-  else
-    echo "$CC $CROSS_CFLAGS cannot compile 128-bit vector arithmetic, disabling"
-    echo "BLACKLIST += $(ls *CP128*.c *_128.c *_Vec128.c | xargs)" >> Makefile.config
-    echo "#define IS_ARM_7 1" >> config.h
-    echo "#define Lib_IntVector_Intrinsics_vec128 void *" >> config.h
-  fi
-fi'
 
 if detect_x86; then
   # Just print information: none of the above build options are supported on x86
   echo "... detected x86 platform"
+  # TODO: can probably detect intrinsics here too and try to enable them!
 fi
-
-: '
-if detect_x86; then
-  echo "... detected x86 platform"
-  echo "... $build_target does not support 256-bit arithmetic"
-  echo "BLACKLIST += $(ls *CP256*.c *_256.c *_Vec256.c | xargs)" >> Makefile.config
-  echo "... $build_target does not support legacy vale stubs"
-  echo "BLACKLIST += evercrypt_vale_stubs.c" >> Makefile.config
-  echo "#define Lib_IntVector_Intrinsics_vec256 void *" >> config.h
-  echo "$CC $CROSS_CFLAGS cannot compile 128-bit vector arithmetic, disabling"
-  echo "BLACKLIST += $(ls *CP128*.c *_128.c *_Vec128.c | xargs)" >> Makefile.config
-  echo "#define Lib_IntVector_Intrinsics_vec128 void *" >> config.h
-fi'
 
 if detect_x64; then
   echo "... detected x64 platform"
-  echo "$build_target supports 128-bit and 256-bit arithmetic"
+  echo "... $build_target supports 128-bit and 256-bit AVX/AVX2"
   supports_128=true
-  supports_256=true
   echo "CFLAGS_128 = -mavx" >> Makefile.config
+  supports_256=true
   echo "CFLAGS_256 = -mavx -mavx2" >> Makefile.config
-  echo "$build_target supports legacy vale stubs"
+  # x64 always supports Vale -- this configure script assumes a GCC-like
+  # compiler, meaning that in theory inline assembly should work (rather than
+  # the external linking) BUT some versions of xcode are irremediably broken and
+  # fail with a register allocator error
+  # Note: MSVC compilers don't support inline GCC assembly and are expected to
+  # use their own build system
+  echo "... $build_target supports vale"
   supports_vale=true
   if detect_broken_xcode; then
     echo "found broken XCode version, known to refuse to compile our inline ASM, disabling "
-#    echo "#define BROKEN_INLINE_ASM 1" >> config.h
   else
     echo "... not using known buggy Apple LLVM build"
-    echo "$build_target supports our inline ASM"
+    echo "... $build_target supports our inline ASM"
     supports_inline_asm=true
   fi
-  if ! check_no_bug81300; then
-    echo "found broken GCC < 5.5 with bug 81300, disabling subborrow + addcarry"
-    echo "#define BROKEN_INTRINSICS 1" >> config.h # TODO: supports_intrinsics
-  else
-    echo "... using a non-buggy GCC"
-  fi
-else
-  # TODO: not sure about that one
-  echo "$build_target does not support x64 assembly, disabling Curve64"
-  echo "BLACKLIST += Hacl_Curve25519_64.c $(ls Hacl_HPKE_Curve64_*.c | xargs)" >> Makefile.config
-  echo "$build_target does not support _addcarry_u64, using a C implementation"
-  echo "#define BROKEN_INTRINSICS 1" >> config.h
-  echo "#define IS_NOT_X64 1" >> config.h
 fi
 
-: '
-if ! detect_x64; then
-  echo "$build_target does not support x64 assembly, disabling Curve64"
-  echo "BLACKLIST += Hacl_Curve25519_64.c $(ls Hacl_HPKE_Curve64_*.c | xargs)" >> Makefile.config
-  echo "$build_target does not support _addcarry_u64, using a C implementation"
-  echo "#define BROKEN_INTRINSICS 1" >> config.h
-  echo "#define IS_NOT_X64 1" >> config.h
-else
-  if detect_broken_xcode; then
-    echo "found broken XCode version, known to refuse to compile our inline ASM, disabling "
-    echo "#define BROKEN_INLINE_ASM 1" >> config.h
-  else
-    echo "... not using known buggy Apple LLVM build"
-  fi
+if detect_x86 || detect_x64; then
   if ! check_no_bug81300; then
     echo "found broken GCC < 5.5 with bug 81300, disabling subborrow + addcarry"
-    echo "#define BROKEN_INTRINSICS 1" >> config.h
   else
+    supports_intrinsics=true
     echo "... using a non-buggy GCC"
   fi
-fi'
+fi
 
-if [ $supports_128 == false ]; then
+if ! $supports_intrinsics; then
+  echo "$build_target does not support _addcarry_u64, using a C implementation"
+  echo "#define BROKEN_INTRINSICS 1" >> config.h
+fi
+
+if ! $supports_vale; then
+  # All reference to Vale symbols are properly guarded in the EverCrypt layer by
+  # ifdef TARGET_X64 -- with the exception of Curve25519, which needs to be
+  # disabled by the build system since it contains unguarded references to Vale
+  # symbols.
+  echo "$build_target does not support x64 assembly, disabling Curve64"
+  echo "BLACKLIST += Hacl_Curve25519_64.c $(ls Hacl_HPKE_Curve64_*.c | xargs)" >> Makefile.config
+  echo "$build_target does not support legacy vale stubs"
+  echo "BLACKLIST += evercrypt_vale_stubs.c" >> Makefile.config
+else
+  echo "#define SUPPORTS_VALE 1" >> config.h
+fi
+
+if ! $supports_inline_asm; then
+    echo "#define BROKEN_INLINE_ASM 1" >> config.h
+fi
+
+if ! $supports_128; then
   echo "$CC $CROSS_CFLAGS cannot compile 128-bit vector arithmetic, disabling"
   echo "BLACKLIST += $(ls *CP128*.c *_128.c *_Vec128.c | xargs)" >> Makefile.config
   echo "#define Lib_IntVector_Intrinsics_vec128 void *" >> config.h
+else
+  echo "#define SUPPORTS_128 1" >> config.h
 fi
 
-if [ $supports_256 == false ]; then
-  echo "... $build_target does not support 256-bit arithmetic"
+if ! $supports_256; then
+  echo "$build_target does not support 256-bit arithmetic"
   echo "BLACKLIST += $(ls *CP256*.c *_256.c *_Vec256.c | xargs)" >> Makefile.config
   echo "#define Lib_IntVector_Intrinsics_vec256 void *" >> config.h
-fi
-
-if [ $supports_vale == false ]; then
-  echo "... $build_target does not support legacy vale stubs"
-  echo "BLACKLIST += evercrypt_vale_stubs.c" >> Makefile.config
-fi
-
-if [ $supports_inline_asm == false ]; then
-    echo "#define BROKEN_INLINE_ASM 1" >> config.h
+else
+  echo "#define SUPPORTS_256 1" >> config.h
 fi
 
 if ! detect_uint128; then
