Shorter, compact Makefile; remove 200 lines of copy-paste for each individual test.

diff --git a/specs/Makefile b/specs/Makefile
--- a/specs/Makefile
+++ b/specs/Makefile
@@ -1,8 +1,11 @@
 include ../Makefile.include
 
-FSTAR += --record_hints
+OUTPUT_DIR = extracted
 
-# TODO: move the specification tests to their own files
+FSTAR += --record_hints --odir $(OUTPUT_DIR)
+
+# TODO: move the specification tests to their own files so that this becomes a
+# single wildcard
 ROOTS=Spec.GF128.fst Spec.Poly1305.fst Spec.Curve25519.fst Spec.Chacha20.fst \
   Spec.Salsa20.fst Spec.Chacha20Poly1305.fst $(wildcard Spec.*.Test.fst) \
   Spec.Ed25519.fst
@@ -10,188 +13,45 @@ ROOTS=Spec.GF128.fst Spec.Poly1305.fst Spec.Curve25519.fst Spec.Chacha20.fst \
 # TODO: decide what to do with the following (excluded) specs:
 #  Spec.HMAC.SHA2_256.fst Spec.HMAC.SHA2_384.fst Spec.HMAC.SHA2_512.fst
 
-# Stage 0: always generate the dependency file
+# Always generate the dependency file
 .PHONY: .depend
 .depend:
-	$(FSTAR) --dep full $(ROOTS) --extract '* -Prims -FStar' > $@
+	$(FSTAR) --dep full $(ROOTS) --extract '* -Prims -FStar +FStar.Endianness' > $@
 
 include .depend
 
 ALL_CHECKED_FILES = $(addsuffix .checked,$(ROOTS))
 
 %.checked:
-	$(FSTAR) $< --use_hints --record_hints && \
+	$(FSTAR) $< && \
 	touch $@
+
+$(OUTPUT_DIR)/%.ml:
+	$(FSTAR) $(subst .checked,,$<) --codegen OCaml --extract_module $(subst .fst.checked,,$(notdir $<))
 
 all: $(ALL_CHECKED_FILES)
 	echo $^
 
-test: $(ALL_ML_FILES)
+test: $(subst .,_,$(patsubst %.fst,test-%,$(ROOTS)))
 
-################################################################################
+test-%: $(OUTPUT_DIR)/%_AutoTest.exe
+	$<
 
-.PHONY=lib all
+OCAMLOPT += -I $(OUTPUT_DIR) -I $(HACL_KREMLIN)
 
-# OCaml variables
-OCAMLOPT := $(OCAMLOPT) -w -8-20-26-28-10
-OCAML_INCLUDES=-I ../code/lib/ml ../code/lib/ml/hacllib.cmxa
+# Can't be super subtle here... because the F* dependency analysis doesn't give
+# us a way to name the cmx dependencies of a given module
+ALL_CMX_FILES = $(patsubst %.ml,%.cmx,$(shell echo $(ALL_ML_FILES) | tac))
 
-all_: lib
-	$(MAKE)	poly1305.exe chacha20.exe salsa20.exe chacha20poly1305.exe gf128.exe ed25519.exe curve25519.exe sha2_256.exe sha2_384.exe sha2_512.exe hmac_sha2_256.exe hmac_sha2_384.exe hmac_sha2_512.exe sha2.exe hmac_sha2.exe
+$(OUTPUT_DIR)/%_AutoTest.exe: $(ALL_CMX_FILES) $(OUTPUT_DIR)/%_AutoTest.ml
+	$(OCAMLOPT) $^ -o $@
 
-lib:
-	$(MAKE) -C ../code/lib/ml
+%.cmx: %.ml
+	$(OCAMLOPT) -c $< -o $@
 
-
-EXTRACTED=FStar_Seq_Base.ml FStar_Seq.ml FStar_Seq_Properties.ml FStar_Math_Lib.ml FStar_BitVector.ml FStar_UInt.ml
-
-NOEXTRACT=$(FSTAR_DEFAULT_ARGS) $(addprefix --no_extract Hacl., UInt64 UInt32 UInt8)
-
-SPEC_FILES=	Spec.Chacha20.Lemmas.fst \
-		Spec.Chacha20.fst \
-		Spec.Chacha20_vec.fst \
-		Spec.Chacha20Poly1305.fst \
-		Spec.CTR.fst \
-		Spec.Curve25519.Lemmas.fst \
-		Spec.Curve25519.fst \
-		Spec.GaloisField.fst \
-		Spec.GF128.fst \
-		Spec.HSalsa20.fst \
-		Spec.Lib.fst \
-		Spec.Poly1305.fst \
-		Spec.Poly1305.Lemmas.fst \
-		Spec.Salsa20.fst \
-		Spec.SHA2.fst \
-		Spec.SHA2.Constants.fst \
-		Spec.Ed25519.fst
-
-hints: $(addsuffix .hints, $(SPEC_FILES))
-verify: $(addsuffix -verify, $(SPEC_FILES))
-all-hints: hints
-all-ver: verify
-
-FSTAR_EXTRACT=$(FSTAR) --codegen OCaml --lax $(NOEXTRACT)
-
-gf128.exe: Spec.GF128.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p gf128-spec
-	$(FSTAR_EXTRACT) --odir gf128-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else failwith "Test failed\n")' >> gf128-spec/Spec_GF128.ml
-	$(OCAMLOPT) -I gf128-spec $(OCAML_INCLUDES) gf128-spec/FStar_Endianness.ml gf128-spec/Spec_GaloisField.ml gf128-spec/Spec_GF128.ml -o gf128.exe
-	./gf128.exe
-
-poly1305.exe: Spec.Poly1305.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p poly-spec
-	$(FSTAR_EXTRACT) --odir poly-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else failwith "Test failed\n")' >> poly-spec/Spec_Poly1305.ml
-	$(OCAMLOPT) -I poly-spec $(OCAML_INCLUDES) poly-spec/FStar_Endianness.ml poly-spec/Spec_Poly1305_Lemmas.ml poly-spec/Spec_Poly1305.ml -o poly1305.exe
-	./poly1305.exe
-
-curve25519.exe: Spec.Curve25519.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p curve25519-spec
-	$(FSTAR_EXTRACT) --odir curve25519-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else failwith "Test failed\n")' >> curve25519-spec/Spec_Curve25519.ml
-	$(OCAMLOPT) -I curve25519-spec $(OCAML_INCLUDES) curve25519-spec/FStar_Endianness.ml curve25519-spec/Spec_Loops.ml curve25519-spec/Spec_Lib.ml curve25519-spec/Spec_Curve25519.ml -o curve25519.exe
-	./curve25519.exe
-
-chacha20.exe: Spec.Chacha20.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p chacha-spec
-	$(FSTAR_EXTRACT) --odir chacha-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else failwith "Test failed\n")' >> chacha-spec/Spec_Chacha20.ml
-	$(OCAMLOPT) -I chacha-spec $(OCAML_INCLUDES) chacha-spec/FStar_Endianness.ml chacha-spec/Spec_Loops.ml chacha-spec/Seq_Create.ml chacha-spec/Spec_Lib.ml chacha-spec/Spec_CTR.ml chacha-spec/Spec_Chacha20.ml -o chacha20.exe
-	./chacha20.exe
-
-salsa20.exe: Spec.Salsa20.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p salsa-spec
-	$(FSTAR_EXTRACT) --odir salsa-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else failwith "Test failed\n")' >> salsa-spec/Spec_Salsa20.ml
-	$(OCAMLOPT) -I salsa-spec $(OCAML_INCLUDES) salsa-spec/FStar_Endianness.ml salsa-spec/Spec_Loops.ml salsa-spec/Seq_Create.ml salsa-spec/Spec_Lib.ml salsa-spec/Spec_CTR.ml salsa-spec/Spec_Salsa20.ml -o salsa20.exe
-	./salsa20.exe
-
-chacha20poly1305.exe: Spec.Chacha20Poly1305.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p chacha-poly-spec
-	$(FSTAR_EXTRACT) --odir chacha-poly-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else failwith "Test failed\n")' >> chacha-poly-spec/Spec_Chacha20Poly1305.ml
-	$(OCAMLOPT) -I chacha-poly-spec $(OCAML_INCLUDES) chacha-poly-spec/FStar_Endianness.ml chacha-poly-spec/Spec_Loops.ml chacha-poly-spec/Seq_Create.ml chacha-poly-spec/Spec_Lib.ml chacha-poly-spec/Spec_CTR.ml chacha-poly-spec/Spec_Chacha20.ml chacha-poly-spec/Spec_Poly1305_Lemmas.ml chacha-poly-spec/Spec_Poly1305.ml chacha-poly-spec/Spec_Chacha20Poly1305.ml -o chacha20poly1305.exe
-	./chacha20poly1305.exe
-
-sha2.exe: Spec.SHA2.Test.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p sha2-spec
-	$(FSTAR_EXTRACT) --odir sha2-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> sha2-spec/Spec_SHA2_Test.ml
-	$(OCAMLOPT) -I sha2-spec $(OCAML_INCLUDES) sha2-spec/FStar_Endianness.ml sha2-spec/Spec_Loops.ml sha2-spec/Spec_Lib.ml sha2-spec/Seq_Create.ml sha2-spec/Spec_SHA2.ml sha2-spec/Spec_SHA2_Test.ml -o sha2.exe
-	./sha2.exe
-
-sha2_256.exe: Spec.SHA2_256.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p sha2_256-spec
-	$(FSTAR_EXTRACT) --odir sha2_256-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> sha2_256-spec/Spec_SHA2_256.ml
-	$(OCAMLOPT) -I sha2_256-spec $(OCAML_INCLUDES) sha2_256-spec/FStar_Endianness.ml sha2_256-spec/Spec_Loops.ml sha2_256-spec/Spec_Lib.ml sha2_256-spec/Seq_Create.ml sha2_256-spec/Spec_SHA2_256.ml -o sha2_256.exe
-	./sha2_256.exe
-
-sha2_384.exe: Spec.SHA2_384.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p sha2_384-spec
-	$(FSTAR_EXTRACT) --odir sha2_384-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> sha2_384-spec/Spec_SHA2_384.ml
-	$(OCAMLOPT) -I sha2_384-spec $(OCAML_INCLUDES) sha2_384-spec/FStar_Endianness.ml sha2_384-spec/Spec_Loops.ml sha2_384-spec/Spec_Lib.ml sha2_384-spec/Seq_Create.ml sha2_384-spec/Spec_SHA2_384.ml -o sha2_384.exe
-	./sha2_384.exe
-
-sha2_512.exe: Spec.SHA2_512.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p sha2_512-spec
-	$(FSTAR_EXTRACT) --odir sha2_512-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> sha2_512-spec/Spec_SHA2_512.ml
-	$(OCAMLOPT) -I sha2_512-spec $(OCAML_INCLUDES) sha2_512-spec/FStar_Endianness.ml sha2_512-spec/Spec_Loops.ml sha2_512-spec/Spec_Lib.ml sha2_512-spec/Seq_Create.ml sha2_512-spec/Spec_SHA2_512.ml -o sha2_512.exe
-	./sha2_512.exe
-
-hmac_sha2.exe: Spec.HMAC.Test.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p hmac-sha2-spec
-	$(FSTAR_EXTRACT) --odir hmac-sha2-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> hmac-sha2-spec/Spec_HMAC_Test.ml
-	$(OCAMLOPT) -I hmac-sha2-spec $(OCAML_INCLUDES) hmac-sha2-spec/FStar_Endianness.ml hmac-sha2-spec/Spec_Loops.ml hmac-sha2-spec/Spec_Lib.ml hmac-sha2-spec/Seq_Create.ml hmac-sha2-spec/Spec_SHA2.ml hmac-sha2-spec/Spec_HMAC.ml hmac-sha2-spec/Spec_HMAC_Test.ml -o hmac_sha2.exe
-	./hmac_sha2.exe
-
-hmac_sha2_256.exe: Spec.HMAC.SHA2_256.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p hmac-sha2_256-spec
-	$(FSTAR_EXTRACT) --odir hmac-sha2_256-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> hmac-sha2_256-spec/Spec_HMAC_SHA2_256.ml
-	$(OCAMLOPT) -I hmac-sha2_256-spec $(OCAML_INCLUDES) hmac-sha2_256-spec/FStar_Endianness.ml hmac-sha2_256-spec/Spec_Loops.ml hmac-sha2_256-spec/Spec_Lib.ml hmac-sha2_256-spec/Seq_Create.ml hmac-sha2_256-spec/Spec_SHA2_256.ml hmac-sha2_256-spec/Spec_HMAC_SHA2_256.ml -o hmac_sha2_256.exe
-	./hmac_sha2_256.exe
-
-hmac_sha2_384.exe: Spec.HMAC.SHA2_384.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p hmac-sha2_384-spec
-	$(FSTAR_EXTRACT) --odir hmac-sha2_384-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> hmac-sha2_384-spec/Spec_HMAC_SHA2_384.ml
-	$(OCAMLOPT) -I hmac-sha2_384-spec $(OCAML_INCLUDES) hmac-sha2_384-spec/FStar_Endianness.ml hmac-sha2_384-spec/Spec_Loops.ml hmac-sha2_384-spec/Spec_Lib.ml hmac-sha2_384-spec/Seq_Create.ml hmac-sha2_384-spec/Spec_SHA2_384.ml hmac-sha2_384-spec/Spec_HMAC_SHA2_384.ml -o hmac_sha2_384.exe
-	./hmac_sha2_384.exe
-
-hmac_sha2_512.exe: Spec.HMAC.SHA2_512.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p hmac-sha2_512-spec
-	$(FSTAR_EXTRACT) --odir hmac-sha2_512-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> hmac-sha2_512-spec/Spec_HMAC_SHA2_512.ml
-	$(OCAMLOPT) -I hmac-sha2_512-spec $(OCAML_INCLUDES) hmac-sha2_512-spec/FStar_Endianness.ml hmac-sha2_512-spec/Spec_Loops.ml hmac-sha2_512-spec/Spec_Lib.ml hmac-sha2_512-spec/Seq_Create.ml hmac-sha2_512-spec/Spec_SHA2_512.ml hmac-sha2_512-spec/Spec_HMAC_SHA2_512.ml -o hmac_sha2_512.exe
-	./hmac_sha2_512.exe
-
-ed25519.exe: Spec.SHA512.fst Spec.Ed25519.fst
-	$(MAKE) -C ../code/lib/ml
-	mkdir -p ed25519-spec
-	$(FSTAR_EXTRACT) --expose_interfaces --odir ed25519-spec $^
-	@echo 'let _ = print_string (if test() then "SUCCESS\n" else "FAILURE\n")' >> ed25519-spec/Spec_Ed25519.ml
-	$(OCAMLOPT) -I ed25519-spec  $(OCAML_INCLUDES) $(addprefix ed25519-spec/, FStar_Endianness.ml Spec_Loops.ml Spec_Lib.ml Spec_Curve25519.ml Seq_Create.ml Spec_SHA2_512.ml Spec_SHA512.ml Spec_Ed25519.ml) -o ed25519.exe
-	./ed25519.exe
+$(OUTPUT_DIR)/%_AutoTest.ml:
+	echo "if not ($*.test ()) then (print_endline \"$* failed\"; exit 1)" > $@
 
 clean:
-	$(MAKE) -C ../code/lib/ml clean
-	rm -rf *.cmi *.cmo *.cmx *.o *~ *.out *.exe poly-spec chacha-spec chacha-poly-spec salsa-spec gf128-spec curve25519-spec sha2-spec sha2_256-spec sha2_384-spec sha2_512-spec hmac-sha2-spec hmac-sha2_256-spec hmac-sha2_384-spec hmac-sha2_512-spec ed25519-spec
+	rm -rf $(OUTPUT_DIR)
+	rm -rf *.checked
