Fix docker file

diff --git a/.docker/build/linux/Dockerfile b/.docker/build/linux/Dockerfile
--- a/.docker/build/linux/Dockerfile
+++ b/.docker/build/linux/Dockerfile
@@ -13,8 +13,12 @@ FROM fstar-linux:${COMMITID}
 ARG BUILDLOGFILE
 ARG MAXTHREADS
 ARG TARGET
+ARG BRANCHNAME
+ARG COMMITID
 
 RUN export FSTAR_HOME=${MYHOME}/FStar
+
+WORKDIR ${MYHOME}/FStar
 
 # Do some cleanup
 RUN rm -rf hacl-star
@@ -37,9 +41,20 @@ RUN rm -f commitinfofilename.json
 RUN mkdir ${MYHOME}/FStar/hacl-star
 COPY --chown=everest / ${MYHOME}/FStar/hacl-star/
 
-# Hacl make calls git clean, which will delete buildlogfile.txt
-# Because of that we will first output on the parent folder
-WORKDIR ${MYHOME}/FStar
+# Do another cleanup
+RUN rm ${MYHOME}/FStar/hacl-star/Dockerfile
+RUN rm ${MYHOME}/FStar/hacl-star/build_helper.sh
+RUN rm ${MYHOME}/FStar/hacl-star/build.sh
+RUN rm ${MYHOME}/FStar/hacl-star/id_rsa
+RUN rm ${MYHOME}/FStar/hacl-star/commitinfofilename.json
+
+# ADD SSH KEY
+RUN mkdir -p ${MYHOME}/.ssh
+RUN chown everest ${MYHOME}/.ssh
+RUN chmod 700 ${MYHOME}/.ssh
+COPY --chown=everest id_rsa ${MYHOME}/.ssh/id_rsa
+RUN chmod 600 ${MYHOME}/.ssh/id_rsa
+RUN eval $(ssh-agent)
 
 COPY --chown=everest build.sh ${MYHOME}/FStar/build.sh
 RUN chmod +x build.sh
@@ -47,7 +62,8 @@ COPY --chown=everest build_helper.sh ${MYHOME}/FStar/build_helper.sh
 RUN chmod +x build_helper.sh
 
 RUN echo $(date -u '+%Y-%m-%d %H:%M:%S') >> ${BUILDLOGFILE}
-RUN ./build_helper.sh ${TARGET} ${BUILDLOGFILE} ${MAXTHREADS} || true
+RUN echo "FStar version => ${COMMITID}" >> ${BUILDLOGFILE}
+RUN ./build_helper.sh ${TARGET} ${BUILDLOGFILE} ${MAXTHREADS} ${BRANCHNAME} || true
 RUN echo $(date -u '+%Y-%m-%d %H:%M:%S') >> ${BUILDLOGFILE}
 
 # Generate query-stats.
@@ -57,3 +73,6 @@ RUN bash -c ".scripts/query-stats.py -f ${BUILDLOGFILE} -F html -o log_no_replay
 # Worst offenders (longest times)
 RUN bash -c ".scripts/query-stats.py -f ${BUILDLOGFILE} -F html -o log_worst.html -c -g -n 10"
 
+# Remove ssh identities.
+RUN rm ${MYHOME}/.ssh/id_rsa
+RUN eval $(ssh-agent) && ssh-add -D
